package exporter

import (
	"bufio"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

type DesignExporter struct {
	db           *sql.DB
	outputDir    string
	compress     bool
	databaseName string
}

func NewDesignExporter(db *sql.DB, outputDir string, compress bool, databaseName string) *DesignExporter {
	return &DesignExporter{
		db:           db,
		outputDir:    outputDir,
		compress:     compress,
		databaseName: databaseName,
	}
}

func (d *DesignExporter) ExportTables(tables []string) error {
	file, err := d.createFile("design_tables.sql")
	if err != nil {
		return err
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- Compatible with MySQL 5.7+ / 8.0+\n")
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n")
	writer.WriteString("SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;\n")
	writer.WriteString("SET SESSION collation_connection = 'utf8mb4_unicode_ci';\n\n")

	// =========================
	// TABLE STRUCTURES
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- TABLE STRUCTURES\n")
	writer.WriteString("-- ============================================\n\n")

	for _, table := range tables {
		var tableName, createTable string
		query := fmt.Sprintf("SHOW CREATE TABLE `%s`", table)
		err := d.db.QueryRow(query).Scan(&tableName, &createTable)
		if err != nil {
			return fmt.Errorf("failed to get create table for %s: %v", table, err)
		}

		writer.WriteString(fmt.Sprintf("-- Table: %s\n", table))
		writer.WriteString(createTable)
		writer.WriteString(";\n\n")

		// Indexes
		indexes, err := d.getTableIndexes(table)
		if err == nil && len(indexes) > 0 {
			writer.WriteString(fmt.Sprintf("-- Indexes for %s\n", table))
			for _, index := range indexes {
				writer.WriteString(index)
				writer.WriteString(";\n")
			}
			writer.WriteString("\n")
		}
	}

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore safe session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func (d *DesignExporter) ExportViews() error {
	views, err := d.getViews()
	if err != nil {
		return fmt.Errorf("get views failed: %w", err)
	}

	if len(views) == 0 {
		return nil
	}

	file, err := d.createFile("design_views.sql")
	if err != nil {
		return fmt.Errorf("file creation failed: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export (Views)\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n\n")

	// =========================
	// VIEWS
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- VIEWS\n")
	writer.WriteString("-- ============================================\n\n")

	for _, view := range views {
		var (
			viewName   string
			createView string
			charset    string
			collation  string
		)

		query := fmt.Sprintf("SHOW CREATE VIEW `%s`", view)

		err := d.db.QueryRow(query).Scan(
			&viewName,
			&createView,
			&charset,
			&collation,
		)
		if err != nil {
			return fmt.Errorf("view [%s] export failed: %w", view, err)
		}

		// 🔥 IMPORTANT: Remove DEFINER for portability
		// createView = removeDefiner(createView)

		writer.WriteString(fmt.Sprintf("-- View: %s\n", view))
		writer.WriteString(fmt.Sprintf("DROP VIEW IF EXISTS `%s`;\n", view))
		writer.WriteString(createView)
		writer.WriteString(";\n\n")
	}

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func (d *DesignExporter) ExportFunctions() error {
	functions, err := d.getRoutines("FUNCTION")
	if err != nil {
		return fmt.Errorf("get functions failed: %w", err)
	}

	if len(functions) == 0 {
		return nil
	}

	file, err := d.createFile("design_functions.sql")
	if err != nil {
		return fmt.Errorf("file creation failed: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export (Functions)\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n\n")

	// =========================
	// FUNCTIONS
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- FUNCTIONS\n")
	writer.WriteString("-- ============================================\n\n")

	writer.WriteString("DELIMITER $$\n\n")

	for _, fn := range functions {
		query := fmt.Sprintf("SHOW CREATE FUNCTION `%s`", fn)

		rows, err := d.db.Query(query)
		if err != nil {
			return fmt.Errorf("function [%s] query failed: %w", fn, err)
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			return err
		}

		values := make([]interface{}, len(cols))
		valuePtrs := make([]interface{}, len(cols))
		for i := range values {
			valuePtrs[i] = &values[i]
		}

		if rows.Next() {
			if err := rows.Scan(valuePtrs...); err != nil {
				rows.Close()
				return fmt.Errorf("function [%s] scan failed: %w", fn, err)
			}
		}
		rows.Close()

		createSQLBytes, ok := values[1].([]byte)
		if !ok {
			return fmt.Errorf("function [%s] invalid create SQL type", fn)
		}

		createSQL := string(createSQLBytes)

		// 🔥 CRITICAL: Remove DEFINER for portability
		// createSQL = removeDefiner(createSQL)

		writer.WriteString(fmt.Sprintf("-- Function: %s\n", fn))
		writer.WriteString(fmt.Sprintf("DROP FUNCTION IF EXISTS `%s` $$\n", fn))
		writer.WriteString(createSQL)
		writer.WriteString(" $$\n\n")
	}

	writer.WriteString("DELIMITER ;\n\n")

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func (d *DesignExporter) ExportProcedures() error {
	procedures, err := d.getRoutines("PROCEDURE")
	if err != nil {
		return fmt.Errorf("get procedures failed: %w", err)
	}

	if len(procedures) == 0 {
		return nil
	}

	file, err := d.createFile("design_procedures.sql")
	if err != nil {
		return fmt.Errorf("file creation failed: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export (Procedures)\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n\n")

	// =========================
	// PROCEDURES
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- STORED PROCEDURES\n")
	writer.WriteString("-- ============================================\n\n")

	writer.WriteString("DELIMITER $$\n\n")

	for _, proc := range procedures {
		query := fmt.Sprintf("SHOW CREATE PROCEDURE `%s`", proc)

		rows, err := d.db.Query(query)
		if err != nil {
			return fmt.Errorf("procedure [%s] query failed: %w", proc, err)
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			return err
		}

		values := make([]interface{}, len(cols))
		valuePtrs := make([]interface{}, len(cols))
		for i := range values {
			valuePtrs[i] = &values[i]
		}

		if rows.Next() {
			if err := rows.Scan(valuePtrs...); err != nil {
				rows.Close()
				return fmt.Errorf("procedure [%s] scan failed: %w", proc, err)
			}
		}
		rows.Close()

		createSQLBytes, ok := values[1].([]byte)
		if !ok {
			return fmt.Errorf("procedure [%s] invalid create SQL type", proc)
		}

		createSQL := string(createSQLBytes)

		// 🔥 CRITICAL: remove DEFINER
		// createSQL = removeDefiner(createSQL)

		// Optional: make safer across environments
		createSQL = strings.ReplaceAll(createSQL, "SQL SECURITY DEFINER", "SQL SECURITY INVOKER")

		writer.WriteString(fmt.Sprintf("-- Procedure: %s\n", proc))
		writer.WriteString(fmt.Sprintf("DROP PROCEDURE IF EXISTS `%s` $$\n", proc))
		writer.WriteString(createSQL)
		writer.WriteString(" $$\n\n")
	}

	writer.WriteString("DELIMITER ;\n\n")

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func (d *DesignExporter) ExportTriggers() error {
	triggers, err := d.getTriggers()
	if err != nil {
		return fmt.Errorf("get triggers failed: %w", err)
	}

	if len(triggers) == 0 {
		return nil
	}

	file, err := d.createFile("design_triggers.sql")
	if err != nil {
		return fmt.Errorf("file creation failed: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export (Triggers)\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n\n")

	// =========================
	// TRIGGERS
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- TRIGGERS\n")
	writer.WriteString("-- ============================================\n\n")

	writer.WriteString("DELIMITER $$\n\n")

	for _, trg := range triggers {
		query := fmt.Sprintf("SHOW CREATE TRIGGER `%s`", trg)

		rows, err := d.db.Query(query)
		if err != nil {
			return fmt.Errorf("trigger [%s] query failed: %w", trg, err)
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			return err
		}

		values := make([]interface{}, len(cols))
		valuePtrs := make([]interface{}, len(cols))
		for i := range values {
			valuePtrs[i] = &values[i]
		}

		if rows.Next() {
			if err := rows.Scan(valuePtrs...); err != nil {
				rows.Close()
				return fmt.Errorf("trigger [%s] scan failed: %w", trg, err)
			}
		}
		rows.Close()

		// index 2 = Create Trigger
		createSQLBytes, ok := values[2].([]byte)
		if !ok {
			return fmt.Errorf("trigger [%s] invalid create SQL type", trg)
		}

		createSQL := string(createSQLBytes)

		// 🔥 CRITICAL: remove DEFINER
		// createSQL = removeDefiner(createSQL)

		writer.WriteString(fmt.Sprintf("-- Trigger: %s\n", trg))
		writer.WriteString(fmt.Sprintf("DROP TRIGGER IF EXISTS `%s` $$\n", trg))
		writer.WriteString(createSQL)
		writer.WriteString(" $$\n\n")
	}

	writer.WriteString("DELIMITER ;\n\n")

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func (d *DesignExporter) ExportEvents() error {
	events, err := d.getEvents()
	if err != nil {
		return fmt.Errorf("get events failed: %w", err)
	}

	if len(events) == 0 {
		return nil
	}

	file, err := d.createFile("design_events.sql")
	if err != nil {
		return fmt.Errorf("file creation failed: %w", err)
	}
	defer file.Close()

	writer := bufio.NewWriter(file)
	defer writer.Flush()

	// =========================
	// FULL MYSQL EXPORT HEADER
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- MySQL Database Export (Events)\n")
	writer.WriteString(fmt.Sprintf("-- Database: %s\n", d.databaseName))
	writer.WriteString("-- Generated by DesignExporter\n")
	writer.WriteString(fmt.Sprintf("-- Date: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	writer.WriteString("-- ------------------------------------------------------\n\n")

	writer.WriteString("SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT;\n")
	writer.WriteString("SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS;\n")
	writer.WriteString("SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION;\n")
	writer.WriteString("SET NAMES utf8mb4;\n")
	writer.WriteString("SET @OLD_TIME_ZONE = @@TIME_ZONE;\n")
	writer.WriteString("SET TIME_ZONE = '+00:00';\n")
	writer.WriteString("SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;\n")
	writer.WriteString("SET UNIQUE_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;\n")
	writer.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n")
	writer.WriteString("SET @OLD_SQL_MODE = @@SQL_MODE;\n")
	writer.WriteString("SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n")
	writer.WriteString("SET @OLD_SQL_NOTES = @@SQL_NOTES;\n")
	writer.WriteString("SET SQL_NOTES = 0;\n")
	writer.WriteString("SET @OLD_AUTOCOMMIT = @@AUTOCOMMIT;\n")
	writer.WriteString("SET AUTOCOMMIT = 0;\n\n")

	// ⚠️ Ensure event scheduler is enabled during import
	writer.WriteString("SET @OLD_EVENT_SCHEDULER=@@EVENT_SCHEDULER;\n")
	writer.WriteString("SET GLOBAL event_scheduler = ON;\n\n")

	// =========================
	// EVENTS
	// =========================
	writer.WriteString("-- ============================================\n")
	writer.WriteString("-- EVENTS\n")
	writer.WriteString("-- ============================================\n\n")

	writer.WriteString("DELIMITER $$\n\n")

	for _, ev := range events {
		query := fmt.Sprintf("SHOW CREATE EVENT `%s`", ev)

		rows, err := d.db.Query(query)
		if err != nil {
			return fmt.Errorf("event [%s] query failed: %w", ev, err)
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			return err
		}

		values := make([]interface{}, len(cols))
		valuePtrs := make([]interface{}, len(cols))
		for i := range values {
			valuePtrs[i] = &values[i]
		}

		if rows.Next() {
			if err := rows.Scan(valuePtrs...); err != nil {
				rows.Close()
				return fmt.Errorf("event [%s] scan failed: %w", ev, err)
			}
		}
		rows.Close()

		createSQLBytes, ok := values[1].([]byte)
		if !ok {
			return fmt.Errorf("event [%s] invalid create SQL type", ev)
		}

		createSQL := string(createSQLBytes)

		// 🔥 CRITICAL: remove DEFINER
		// createSQL = removeDefiner(createSQL)

		writer.WriteString(fmt.Sprintf("-- Event: %s\n", ev))
		writer.WriteString(fmt.Sprintf("DROP EVENT IF EXISTS `%s` $$\n", ev))
		writer.WriteString(createSQL)
		writer.WriteString(" $$\n\n")
	}

	writer.WriteString("DELIMITER ;\n\n")

	// =========================
	// RESTORE SESSION SETTINGS
	// =========================
	writer.WriteString("-- ------------------------------------------------------\n")
	writer.WriteString("-- Restore session settings\n")
	writer.WriteString("-- ------------------------------------------------------\n")

	writer.WriteString("SET GLOBAL event_scheduler = @OLD_EVENT_SCHEDULER;\n")
	writer.WriteString("/*!40103 SET TIME_ZONE='+00:00' */;\n")
	writer.WriteString("/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n")
	writer.WriteString("/*!40014 SET FOREIGN_KEY_CHECKS=1 */;\n")
	writer.WriteString("/*!40014 SET UNIQUE_CHECKS=1 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_CLIENT=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET CHARACTER_SET_RESULTS=utf8mb4 */;\n")
	writer.WriteString("/*!40101 SET COLLATION_CONNECTION=utf8mb4_unicode_ci */;\n")
	writer.WriteString("/*!40111 SET SQL_NOTES=1 */;\n")
	writer.WriteString("/*!40101 SET AUTOCOMMIT=1 */;\n")
	writer.WriteString("COMMIT;\n")

	return nil
}

func removeDefiner(sql string) string {
	re := regexp.MustCompile(`(?i)\s*DEFINER\s*=\s*` +
		"`[^`]+`@`[^`]+`" + // matches `user`@`host`
		`\s*`)

	return re.ReplaceAllString(sql, " ")
}

func (d *DesignExporter) createFile(filename string) (*os.File, error) {
	filepath := filepath.Join(d.outputDir, filename)
	return os.Create(filepath)
}

func (d *DesignExporter) getTableIndexes(table string) ([]string, error) {
	query := `
        SELECT index_name, non_unique, GROUP_CONCAT(column_name ORDER BY seq_in_index) as columns
        FROM information_schema.statistics 
        WHERE table_schema = ? 
        AND table_name = ?
        AND index_name != 'PRIMARY'
        GROUP BY index_name, non_unique
        ORDER BY index_name
    `

	rows, err := d.db.Query(query, d.databaseName, table)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []string
	for rows.Next() {
		var indexName string
		var nonUnique int
		var columns string

		err := rows.Scan(&indexName, &nonUnique, &columns)
		if err != nil {
			return nil, err
		}

		unique := ""
		if nonUnique == 0 {
			unique = "UNIQUE "
		}

		createIndex := fmt.Sprintf("CREATE %sINDEX `%s` ON `%s` (%s)",
			unique, indexName, table, columns)
		result = append(result, createIndex)
	}

	return result, nil
}

func (d *DesignExporter) getViews() ([]string, error) {
	query := `
        SELECT table_name 
        FROM information_schema.views 
        WHERE table_schema = ?
        ORDER BY table_name
    `

	rows, err := d.db.Query(query, d.databaseName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var views []string
	for rows.Next() {
		var view string
		if err := rows.Scan(&view); err != nil {
			return nil, err
		}
		views = append(views, view)
	}

	return views, nil
}

func (d *DesignExporter) getRoutines(routineType string) ([]string, error) {
	query := `
        SELECT routine_name 
        FROM information_schema.routines 
        WHERE routine_schema = ? 
        AND routine_type = ?
        ORDER BY routine_name
    `

	rows, err := d.db.Query(query, d.databaseName, routineType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var routines []string
	for rows.Next() {
		var routine string
		if err := rows.Scan(&routine); err != nil {
			return nil, err
		}
		routines = append(routines, routine)
	}

	return routines, nil
}

func (d *DesignExporter) getRoutineSQL(name, routineType string) (string, error) {
	query := fmt.Sprintf("SHOW CREATE %s `%s`", routineType, name)
	var routineName, createSQL string
	err := d.db.QueryRow(query).Scan(&routineName, &createSQL)
	if err != nil {
		return "", err
	}
	return createSQL, nil
}

func (d *DesignExporter) getTriggers() ([]string, error) {
	query := `
        SELECT trigger_name 
        FROM information_schema.triggers 
        WHERE trigger_schema = ?
        ORDER BY trigger_name
    `

	rows, err := d.db.Query(query, d.databaseName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var triggers []string
	for rows.Next() {
		var trigger string
		if err := rows.Scan(&trigger); err != nil {
			return nil, err
		}
		triggers = append(triggers, trigger)
	}

	return triggers, nil
}

func (d *DesignExporter) getEvents() ([]string, error) {
	query := `
        SELECT event_name 
        FROM information_schema.events 
        WHERE event_schema = ?
        ORDER BY event_name
    `

	rows, err := d.db.Query(query, d.databaseName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var events []string
	for rows.Next() {
		var event string
		if err := rows.Scan(&event); err != nil {
			return nil, err
		}
		events = append(events, event)
	}

	return events, nil
}
